/**
 * Created by IntelliJ IDEA.
 * User: ashevenkov
 * Date: 19.02.14
 * Time: 19:17
 */

import ru.alterloki.Util;

/**
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 *
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 *
 * Let us list the factors of the first seven triangle numbers:
 *
 *  1: 1
 *  3: 1,3
 *  6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * We can see that 28 is the first triangle number to have over five divisors.
 *
 * What is the value of the first triangle number to have over five hundred divisors?
 *
 * @author ashevenkov
 */
public class Problem12 {
    /**
     *  1 * 1
     *  3 * 1
     *  3 * 2
     *  5 * 2
     *  5 * 3
     *  7 * 3
     *  7 * 4
     *  9 * 4
     * @param args
     */

    public static void main(String[] args) {
        int[] primes = Util.generatePrimes(1000000);
        int nCount = 0;
        int first = 1;
        int second = 1;
        boolean flag = true;
        while(nCount < 500) {
            int num = first * second;
            if(flag) {
                first += 2;
            } else {
                second++;
            }
            flag = !flag;
            nCount = Util.divisorCount(num, primes);
            if(nCount > 500) {
                System.out.println(num);
            }
        }
    }

}
