/**
 * Created by IntelliJ IDEA.
 * User: ashevenkov
 * Date: 14.02.14
 * Time: 22:50
 */

/**
 * Even Fibonacci numbers
 * Problem 2
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
 * the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 * @author ashevenkov
 */
public class Problem2 {
    public static void main(String[] args) {
        int fibPrev = 1;
        int fibNum = 1;
        long result = 0;
        while(fibNum < 4000000) {
            if(fibNum % 2 == 0) {
                result += fibNum;
            }
            int newFibNum = fibNum + fibPrev;
            fibPrev = fibNum;
            fibNum = newFibNum;
        }
        System.out.println(result);
    }
}
